spring:
  application:
    name: farm
  mvc:
    view:
       prefix: /WEB-INF/views/
       suffix: .jsp
  config:
    import: classpath:info.yml
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${oracle.url}
    username: ${oracle.username}
    password: ${oracle.password}
server:
  servlet:
     context-path: /farm

mybatis:
  mapper-locations: classpath:sqlmap/*Mapper.xml
#  config-location: classpath:sqlmap/typeConfig.xml